### ISSUE TITLE
Error in cement update with REMIND scenarios

### ISSUE THREAD

**Issue by dbantje** [polca/premise#233]
On `2.3.0.dev1_intervs` I now get a KeyError during `cement` updates:

```
Traceback (most recent call last):
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'cement, dry feed rotary kiln, efficient, with MEA CCS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/indexes.py", line 772, in sel
    indexer = self.index.get_loc(label_value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'cement, dry feed rotary kiln, efficient, with MEA CCS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/p/projects/ariadne/scenarioLCA/01_run_premise_from_config.py", line 151, in <module>
    ndb.create_datapackage(name=outputdir+f"{dirname}/{fname}", transformations=transformations,
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/pathways.py", line 82, in create_datapackage
    self.datapackage.update(transformations, which_interventions)
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/new_database.py", line 1082, in update
    scenario = update_func(scenario, *fixed_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/cement.py", line 50, in _update_cement
    cement.build_clinker_production_datasets()
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/cement.py", line 144, in build_clinker_production_datasets
    self.process_and_add_activities(
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/transformation.py", line 1102, in process_and_add_activities
    production_volumes.sel(variables=technology)
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/dataarray.py", line 1614, in sel
    ds = self._to_temp_dataset().sel(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/dataset.py", line 3091, in sel
    query_results = map_index_queries(
                    ^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/indexing.py", line 190, in map_index_queries
    results.append(index.sel(labels, **options))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/indexes.py", line 774, in sel
    raise KeyError(
KeyError: "not all values found in index 'variables'. Try setting the `method` keyword argument (example: method='nearest')."
```

I suspect that the changes in commit 636aa33 are causing it. It seems that now production volumes are used more broadly, but current REMIND scenarios don't have the variable `Production|Industry|Cement w CCS` in them. In fact, I got the warning message
```
The following variables are missing from the IAM file: /p/projects/ariadne/scenarioLCA/remind_runs
+----------------------------------+
|             Variable             |
+----------------------------------+
| Production|Industry|Cement w CCS |
+----------------------------------+
``` 
already before, but it never led to errors.

Is it possible to include an exception here? Or might the mapping file be simply wrong?

**Comment by romainsacchi** [comment]
I see. That's because I post-process the scenario file to create a variable called Production|Industry|Cement w CCS based on gross vs. sequestered emissions from the cement sector. How do you want to deal with this? I can insert a check to skip that step in the cement update.

**Comment by dbantje** [comment]
Ah, good to know! I think for now I can switch back to the default scenarios then. Would it be possible to just add the post-processing to premise (checking whether the variable doesn't exist yet)?

**Comment by romainsacchi** [comment]
This https://github.com/polca/premise/commit/91542d5ba5cf0cab3d83bf91b2bc9a661b72f837 should fix it. Let me know if not.

**Comment by dbantje** [comment]
Hi Romain!

Just realized that this does not fix the issue when a custom REMIND scenario is loaded (I assume because the `cement.yaml` file is still untouched, so premise thinks REMIND (without your post-processing) knows about cement w CCS)).

**Comment by romainsacchi** [comment]
So you're still getting:

Traceback (most recent call last):
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/indexes.py", line 772, in sel
    indexer = self.index.get_loc(label_value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'cement, dry feed rotary kiln, efficient, with MEA CCS'

?

**Comment by dbantje** [comment]
Yes, the traceback is

```
Traceback (most recent call last):
  File "/p/projects/ariadne/scenarioLCA/01_run_premise_from_config.py", line 151, in <module>
    ndb.create_datapackage(name=outputdir+f"{dirname}/{fname}", transformations=transformations,
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/pathways.py", line 82, in create_datapackage
    self.datapackage.update(transformations, which_interventions)
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/new_database.py", line 1082, in update
    scenario = update_func(scenario, *fixed_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/cement.py", line 50, in _update_cement
    cement.build_clinker_production_datasets()
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/cement.py", line 144, in build_clinker_production_datasets
    self.process_and_add_activities(
  File "/p/projects/ariadne/scenarioLCA/software/premise/premise/transformation.py", line 1112, in process_and_add_activities
    production_volumes.sel(variables=technology)
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/dataarray.py", line 1614, in sel
    ds = self._to_temp_dataset().sel(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/dataset.py", line 3091, in sel
    query_results = map_index_queries(
                    ^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/indexing.py", line 190, in map_index_queries
    results.append(index.sel(labels, **options))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/scenarioLCA/lib/python3.11/site-packages/xarray/core/indexes.py", line 774, in sel
    raise KeyError(
KeyError: "not all values found in index 'variables'. Try setting the `method` keyword argument (example: method='nearest')."
```

**Comment by romainsacchi** [comment]
@dbantje can you add me as a collaborator to your fork, so that I can push a fix?

**Comment by dbantje** [comment]
Sure! I've already commented out the relevant lines in the variables mapping.

**Comment by romainsacchi** [comment]
@dbantje I've created a new branch in your repo: interventionpaper_v5.
Let me know if that runs fine.

**Comment by dbantje** [comment]
@romainsacchi That works fine, thank you!
